// Deterministic feedback unit checks, independent of the career RNG and save schema.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../js/feedback.js'),'utf8');
function boot(saved,blocked=false){let time=0,created=0,starts=0,stops=0;const events={},timers=new Map(),frames=new Map(),store={...saved},gains=[];let serial=0;
const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(v){assert(v<=.18)},exponentialRampToValueAtTime(){}});
class AC{constructor(){created++;this.state='running';this.currentTime=0;this.destination={};}createGain(){const n={gain:param(),connect(){},disconnect(){}};gains.push(n);return n;}createOscillator(){return {frequency:param(),connect(){},disconnect(){},start(){starts++},stop(){stops++}};}resume(){return Promise.resolve();}}
const document={hidden:false,body:{},documentElement:{dataset:{}},addEventListener(n,f){events[n]=f;}};
const ctx={document,matchMedia:()=>({matches:false}),localStorage:{getItem(k){if(blocked)throw Error();return store[k]||null},setItem(k,v){store[k]=v}},performance:{now:()=>time},MutationObserver:class{observe(){}},setTimeout(fn){timers.set(++serial,fn);return serial},clearTimeout(id){timers.delete(id)},requestAnimationFrame(fn){frames.set(++serial,fn);return serial},cancelAnimationFrame(id){frames.delete(id)},AudioContext:AC,addEventListener(n,f){events[n]=f;},Math:Object.assign(Object.create(Math),{random(){throw Error('Feedback used gameplay RNG')}})};ctx.window=ctx;vm.runInNewContext(source,ctx);return{F:ctx.Feedback,events,document,store,timers,frames,gains,tick(){time+=100},counts:()=>({created,starts,stops})};}
const a=boot();assert.equal(a.F.play('bat'),false);assert.equal(a.counts().created,0);a.events.pointerdown({isTrusted:false});assert.equal(a.counts().created,0);a.events.keydown({isTrusted:true});assert(a.F.play('select'));assert(!a.F.play('select'));assert(a.F.play('kick'));assert(a.F.play('catch'));assert(a.F.play('good'));assert(!a.F.play('great'));assert.equal(a.counts().starts,4);assert(a.gains[0].gain.value<=.036);a.F.stop();a.tick();assert(a.F.play('great'));
const el={isConnected:true};let calls=0;a.F.later(el,()=>calls++,50);a.F.frame(el,()=>calls++);a.F.clear(el);assert.equal(a.timers.size,0);assert.equal(a.frames.size,0);assert.equal(calls,0);a.document.hidden=true;assert(!a.F.play('bat'));a.events.visibilitychange();
const key=source.match(/var key = '([^']+)'/)[1];const b=boot({[key]:JSON.stringify({muted:true,volume:9,reduced:true})});assert.equal(b.document.documentElement.dataset.reducedMotion,'true');b.events.touchstart({isTrusted:true});assert.equal(b.counts().created,0);assert(!b.F.play('bat'));assert.equal(b.store[key],JSON.stringify({muted:true,volume:9,reduced:true}));boot({[key]:'broken json'});boot({},true);console.log('PASS feedback unit: trusted gesture, quiet gain, throttle, four voices, cancel, hidden, settings, storage failure, no game RNG');
